/* tslint:disable */
// This file is generated
// Do not edit this file

/* tslint:disable */
// This file is generated
// Do not edit this file

import type { IntegrationInstance } from '@botpress/sdk'

import type * as configuration from "./configuration/index"
import type * as actions from "./actions/index"
import type * as channels from "./channels/index"
import type * as events from "./events/index"
import type * as states from "./states/index"
export * as configuration from "./configuration/index"
export * as actions from "./actions/index"
export * as channels from "./channels/index"
export * as events from "./events/index"
export * as states from "./states/index"

export type TelegramtestProps = {
  enabled?: boolean
  config?: configuration.Configuration
}

export type TTelegramtest = {
  name: 'telegramtest'
  version: '0.0.1'
  configuration: configuration.Configuration
  actions: actions.Actions
  channels: channels.Channels
  events: events.Events
  states: states.States
  user: { "tags": { "id": {} }, "creation": { "enabled": false, "requiredTags": [] } }
}

export class Telegramtest implements IntegrationInstance<'telegramtest'> {

  public readonly name = 'telegramtest'
  public readonly version = '0.0.1'
  public readonly id = 'intver_01HGK80ZN36R1ZM0Z4PYT0P4Q9'

  public readonly enabled?: boolean
  public readonly configuration?: configuration.Configuration

  constructor(props?: TelegramtestProps) {
    this.enabled = props?.enabled
    this.configuration = props?.config
  }
}