/* tslint:disable */
// This file is generated
// Do not edit this file

import * as sdk from '@botpress/sdk'
import * as telegramtest from './installations/telegramtest'
export * as telegramtest from './installations/telegramtest'

type TIntegrations = {
  telegramtest: telegramtest.TTelegramtest
}

type BaseStates = sdk.Bot extends sdk.Bot<any, infer TStates, any> ? TStates : never
type BaseEvents = sdk.Bot extends sdk.Bot<any, any, infer TEvents> ? TEvents : never

export class Bot<
  TStates extends BaseStates,
  TEvents extends BaseEvents
> extends sdk.Bot<
    TIntegrations,
    TStates,
    TEvents
> {}